apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: deploymentmetadatas.deployment.foremast.ai
spec:
  group: deployment.foremast.ai
  names:
    kind: DeploymentMetadata
    plural: deploymentmetadatas
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            analyst:
              properties:
                endpoint:
                  type: string
                version:
                  type: string
              required:
              - endpoint
              type: object
            description:
              type: string
            descriptor:
              properties:
                description:
                  type: string
                icons:
                  items:
                    properties:
                      size:
                        type: string
                      src:
                        type: string
                      type:
                        type: string
                    required:
                    - src
                    type: object
                  type: array
                keywords:
                  items:
                    type: string
                  type: array
                links:
                  items:
                    properties:
                      description:
                        type: string
                      url:
                        type: string
                    type: object
                  type: array
                maintainers:
                  items:
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      url:
                        type: string
                    type: object
                  type: array
                notes:
                  type: string
                owners:
                  items:
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      url:
                        type: string
                    type: object
                  type: array
                type:
                  type: string
                version:
                  type: string
              type: object
            hpaScoreTemplates:
              items:
                properties:
                  metrics:
                    items:
                      type: string
                    type: array
                  name:
                    type: string
                required:
                - name
                - metrics
                type: object
              type: array
            logs:
              items:
                properties:
                  filePattern:
                    type: string
                  logName:
                    type: string
                  logType:
                    type: string
                required:
                - logName
                - logType
                type: object
              type: array
            metrics:
              properties:
                dataSourceType:
                  type: string
                endpoint:
                  type: string
                monitoring:
                  items:
                    properties:
                      metricAlias:
                        type: string
                      metricName:
                        type: string
                      metricType:
                        type: string
                    required:
                    - metricName
                    - metricAlias
                    type: object
                  type: array
              required:
              - dataSourceType
              - endpoint
              type: object
          required:
          - analyst
          - metrics
          type: object
        status:
          properties:
            observedGeneration:
              format: int64
              type: integer
          type: object
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
