apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foremast
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  - "deployment.foremast.ai"
  resources:
  - namespaces
  - services
  - endpoints
  - pods
  - replicasets
  - deployments
  - deployments/rollback
  - deployments/scale
  - daemonsets
  - daemonsets/scale
  - statefulsets
  - statefulsets/scale
  - deploymentmonitors
  - deploymentmetadatas
  - rollback
  - events
  verbs:
  - get
  - list
  - watch

---
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foremast
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - deployments
  - deployments/rollback
  - deployments/scale
  - rollback
  - events
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foremast-crd-operator
rules:
- apiGroups:
  - "deployment.foremast.ai"
  resources:
  - deploymentmonitors
  - deploymentmetadatas
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: foremast
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:serviceaccount:foremast
subjects:
- kind: ServiceAccount
  name: default
  namespace: foremast

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: foremast-crd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:serviceaccount:foremast-crd-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: foremast