apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: foremast-examples
  labels:
    app: demo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo

---
apiVersion: deployment.foremast.ai/v1alpha1
kind: DeploymentMonitor
metadata:
  name: demo
  namespace: foremast-examples
spec:
  # Auto rollback or not when unhealthy detected
  remediation:
    option: AutoRollback


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo
  namespace: foremast-examples
spec:
  selector:
    matchLabels:
      app: demo
  endpoints:
  - port: http
    targetPort: 8080
    scheme: http
    path: /actuator/prometheus
