apiVersion: apps/v1
kind: Deployment
metadata:
  name: foremast-trigger
  namespace: foremast
  labels:
    app: foremast-trigger
spec:
  selector:
    matchLabels:
      app: foremast-trigger
  template:
    metadata:
      labels:
        app: foremast-trigger
    spec:
      containers:
      - image: docker.io/kjones43/foremast-trigger:1.2-fpp-das-fpo-dac
        imagePullPolicy: Always
        name: query
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 8011
          name: http
        env:
          - name: FOREMAST_ES_ENDPOINT
            value: http://elasticsearch-discovery.foremast.svc.cluster.local:9200
          - name: FOREMAST_SERVICE_ENDPOINT
            value: http://foremast-service.foremast.svc.cluster.local:8099
            # value: http://10.97.93.44:8099/v1/healthcheck/create
      terminationGracePeriodSeconds: 10
